### ISSUE TITLE
proxrox stop gets stuck

### ISSUE THREAD

**Issue by basti1302** [bripkens/proxrox#14]
`proxrox stop` hangs on my Linux Mint box, reproducible. The nginx processes get killed though, but `proxrox stop` never returns control to the shell. I'm pretty sure it's shelljs' fault, as this one liner also hangs:

```
require('shelljs').exec('pkill -f foobar');
```

It's probably related to https://github.com/arturadib/shelljs/issues/51

On a slightly related note, it feels a little bit brute-force-y to just kill all nginx master processes. It might be quite unlikely, but there could be another, completely unrelated, nginx process around, right?

What about spawning the nginx process via node core's `child_process.spawn` on `proxrox start`, remembering the pid (in the tmp folder), and killing only the process with that pid on `proxrox stop`?

**Comment by bripkens** [comment]
Oh noes :(

I very much like the idea! But then `proxrox stop` could only stop the last started nginx process. Can we come up with a strategy to stop the nginx process which is currently running for a given `.proxrox.yaml` file?

**Comment by basti1302** [comment]
As the issue of killing unrelated nginx instances is not really related to this problem, I'll open a new issue about it to discuss it.
