### ISSUE TITLE
Issue with directory permissions results in 404 on POST

### ISSUE THREAD

**Issue by basti1302** [bripkens/proxrox#17]
I noticed that a POST request that works fine without being proxied through proxrox results in a 404 when proxied through proxrox. Here's what the logs say:

error log:

```
2015/08/08 16:24:48 [crit] 6549#0: *6 open() "/var/lib/nginx/body/0000000001" failed (13: Permission denied), client: 127.0.0.1, server: example, request: "POST /upload HTTP/1.1", host: "localhost:4000", referrer: "http://localhost:4000/"
2015/08/08 16:24:48 [error] 6549#0: *6 open() "/tmp/proxrox/c5f08868-85d1-4599-9e47-1af1bf9b88bb/html/50x.html" failed (2: No such file or directory), client: 127.0.0.1, server: example, request: "POST /upload HTTP/1.1", host: "localhost:4000", referrer: "http://localhost:4000/"
```

access.log

```
127.0.0.1 - - [08/Aug/2015:16:24:48 +0200] "POST /upload HTTP/1.1" 404 420 "http://localhost:4000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/43.0.2357.130 Chrome/43.0.2357.130 Safari/537.36" "2.94"
```

The main issue seems to be `open() "/var/lib/nginx/body/0000000001" failed (13: Permission denied)`. The directory `/var/lib/nginx/body` used to temporary store the request body and on my system, everything under `/var/lib/nginx` is owned by `nobody:root`. When running proxrox/nginx without sudo (I assume proxrox is intended to be run without sudo, right?) then nginx can not create new files there.

I verified this by temporarily chmodding /var/lib/nginx/body to 777, then the POST request works as expected. 

A possible solution might be to set the [client_body_temp_path](http://wiki.nginx.org/HttpCoreModule#client_body_temp_path) directive in the nginx.conf. However, I could guess there might be more, similar cases where nginx needs a tmp dir for something and does not have the correct permissions. (For example, at least [proxy_temp_path](http://wiki.nginx.org/HttpProxyModule#proxy_temp_path) looks suspicious)

**Comment by bripkens** [comment]
Hey Basti,

thanks for bringing this to my attention! I followed your suggestions and specified the temp file paths. This will hopefully solve your issues. Please let me know whether there are any further issues.

New release is already on npmjs.org.

**Comment by basti1302** [comment]
Awesome!

Yes, this solves the issue. Thanks for the quick turn around. :+1:
