### ISSUE TITLE
Add authbind instructions to run proxrox on linux?

### ISSUE THREAD

**Issue by anirudhvarma12** [bripkens/proxrox#44]
Hi, thanks for making this great utility, its an absolutely awesome thing. 

I have been using proxrox on MacOS for quite sometime now, but today I had to setup an environment on Linux (Linux Mint to be specific) and for some reason the default installation instructions did not work for me.

What worked though was using `authbind` to setup proxrox. I would be happy to contribute by opening a PR to suggest this as an alternative approach if that works for you?

**Comment by bripkens** [comment]
Hey @anirudhvarma12,

I am glad to hear that you find it useful! :) 

Your `authbind` suggestion sounds pretty interesting. Linux installation instructions are still one of those harder topics and if you found a good solution to this, I would very much appreciate a PR! :)

**Comment by anirudhvarma12** [comment]
Opened https://github.com/bripkens/proxrox/pull/45
