### ISSUE TITLE
Not redirecting

### ISSUE THREAD

**Issue by susarla12345** [bripkens/proxrox#55]
my proxrox config

proxy:
  - type: 'https'
    from: '/'
    to: 'https://app.*.ai:3000'
    
 
 use case : redirect all requests from app.*.ai to app.*.ai:3000
 
 please help

**Comment by bripkens** [comment]
What you have for `to` is not a supported configuration. These options are forwarded straight to nginx and it has no support for globbing. Also please note, that this does not result in a redirect. Instead, this would result in a reverse proxy that is not visible from within a web browser.
