### ISSUE TITLE
Support ngx_pagespeed for Linux platforms

### ISSUE THREAD

**Issue by bripkens** [bripkens/proxrox#9]
Unfortunately pagespeed does not yet support OS X (https://github.com/pagespeed/ngx_pagespeed/issues/149), but this feature may be very useful for Linux users.

**Comment by jeffkaufman** [comment]
If anyone is working on this and runs into trouble, feel free to tag me and I'll look at it.

**Comment by bripkens** [comment]
Thanks @jeffkaufman, will do when I get to do this :)

**Comment by denji** [comment]
@jeffkaufman Can add a mention in the documentation to write that this module works "only on linux" in comparison conventional modules nginx,
